library resources;

const String AIRPLANE = "airplane.png";
const String LOGO = "logo.png";
const String MANUAL = "manual.png";
const String PEOPLE = "people.png";
const String TRAVEL = "travel.png";
const String USER = "user.png";
const String TEAM = "equipe.jpg";
const String MOTORA = "motora.jpg";
const String TROPHY = "trophy.png";
const String WATER = "cup-water.png";
const String EXERCISE = "dumbbell.png";
const String GIFT = "gift.png";
const String HEALTH = "health.png";
const String HOME = "home.png";
const String NUTRITION = "nutrition.png";
const String WALK = "walk.png";
const String EXERCISE_MAN = "weight-lifter.png";
const String POUND = "pound.png";
const String SLEEP = "sleep.png";
const String PILL = "pill.png";
const String PRESSURE = "pressure.png";
const String WTRUCKER = "wtrucker.png";
const String ACE = "ace.png";